jsx = "react-jsx"
jsxImportSource = "react"

telemetry = false

[serve]
  port = 4001
  hostname = "localhost"

[test]
  framework = "bun:test"
  environment = "node"
  root = "./__tests__"
  coverage = true
